controller_manager:
  ros__parameters:
    update_rate: 200  # Hz - vong dieu khien khop (xem §8 tai lieu)

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

forward_position_controller:
  ros__parameters:
    joints:
      - FR_hip_joint
      - FR_thigh_joint
      - FR_calf_joint
      - FL_hip_joint
      - FL_thigh_joint
      - FL_calf_joint
      - RR_hip_joint
      - RR_thigh_joint
      - RR_calf_joint
      - RL_hip_joint
      - RL_thigh_joint
      - RL_calf_joint
    interface_name: position
